spring:
  datasource:
    url: jdbc:postgresql://localhost:5460/apisecurity_demo
    username: apisecurity
    password: apisecurity
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

  logging:
    pattern:
      console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: logs/my-app-name