@dangerous-api-url=http://localhost:8080/api/dos/v1



#### Get green
GET {{dangerous-api-url}}/green


### Get red
GET {{dangerous-api-url}}/red


### Get colorful
GET {{dangerous-api-url}}/random-colors