
### 
POST http://localhost:8080/api/auth/basic/v1/user
Content-Type: application/json 

{
	"username": "npantelic",
	"password":"password123",
	"displayName": "npntlc"
}

### Get time - valid credentials
GET http://localhost:8080/api/auth/basic/v1/time
Content-Type: application/json
Authorization: Basic bnBhbnRlbGljOnBhc3N3b3JkMTIz

### Get time - invalid credentials
GET http://localhost:8080/api/auth/basic/v1/time
Content-Type: application/json
Authorization: Basic 1234

