### Login
POST http://localhost:8080/api/auth/redis-jwt/v1/login
Content-Type: application/json
Authorization: Basic bnBhbnRlbGljOnBhc3N3b3JkMTIz


### Get time
GET http://localhost:8080/api/auth/redis-jwt/v1/time
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NDNmYzA3YjFkM2EyMmI5OTIyNzg2YTMxNGNiZDNjOCIsImlzcyI6ImFwaXNlY3VyaXR5LmNvbSIsImF1ZCI6WyJodHRwczovL2FwaXNlY3VyaXR5LmNvbSIsImh0dHBzOi8vd3d3LmFwaXNlY3VyaXR5LmNvbSJdLCJleHAiOjE3MzQ5MDEwMzksImR1bW15QXR0cmlidXRlIjpudWxsLCJzYW1wbGVQcml2YXRlQ2xhaW0iOiJqdXN0LXNvbWUtcHJpdmF0ZS1jbGFpbS10by1iZS12YWxpZGF0ZWQiLCJqdGkiOiJiVUJZWldqdWVsd2FVVG9uTXNLRlYyMTN0Ulh1RlcifQ.VgM-ulhR-hoSUdDJkOf95rGyBIw1VHlLsadL9QLycu0



### Logout
DELETE http://localhost:8080/api/auth/redis-jwt/v1/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.9cf34c1de07da7e16ca6143ed7624779e67f0053513018aea28597b9ee9b8451